# Generated by Django 3.0.5 on 2020-06-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200614_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
