# Generated by Django 3.0.5 on 2020-06-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
